### ISSUE TITLE
Question about Cayenne payload format

### ISSUE THREAD

**Issue by sebastianha** [RobPo/lorapaper#2]
I just manages to get my node into my console and I get the following example payload:

`00 01 01  00 04 46 7E`

According to the lines in the "WeatherForecastExample.ino":

https://github.com/RobPo/lorapaper/blob/e1feaa145c14840521f3da360983e378cfb52a38/examples/WeatherForecastExample/WeatherForecastExample.ino#L105

this should be the counter and the voltage as analog Input.

I checked the Cayenne documentation (https://developers.mydevices.com/cayenne/docs/lora/#lora-cayenne-low-power-payload-data-types) which states that Analog Input should have the ID "02" and not "04" as in the payload. I took at look at

https://github.com/RobPo/lorapaper/blob/e1feaa145c14840521f3da360983e378cfb52a38/examples/WeatherForecastExample/Cayenne_LPP.cpp#L134

and I think this line is just wrong. Instead of "LPP_ANALOG_INPUT_SIZE" it should be "LPP_ANALOG_INPUT"

What do you think?

**Comment by sebastianha** [comment]
Now that I changed the value it also shows correctly in the TTN console as
```
{
  "analog_in_0": 219.14,
  "digital_out_0": 0
}
```

I only wonder why the voltage is "219.14". That seems to be incorrect.

**Comment by RobPo** [comment]
Looks good.
You are right the calculation is wrong and should be `LPP.addAnalogInput(0x00, v_scap*3.3/1024*4); `.

**Comment by sebastianha** [comment]
Perhaps another minor thing: according to https://www.arduino.cc/en/Tutorial/ReadAnalogVoltage it should /1023 not /1024 to get a correct reading. I assume *4 is a voltage divider.

**Comment by RobPo** [comment]
Ok just fixed the factor from 1024 to 1023, thanks! 
There is a balanced voltage divider which is connected to BAL pin, which is 50% of the the supercap voltage. The voltage divider is actually not really needed and could be removed in the future (schematics just added).
